# Generated by Django 3.1.7 on 2021-04-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yatenesturnoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.CharField(default='notype', max_length=30),
            preserve_default=False,
        ),
    ]
